### ISSUE TITLE
Tetris...

### ISSUE THREAD

**Issue by slvoog** [saxnbt/SaxOS#6]
I'm checking out SaxOS on [saxnbt.tk/SaxOS/os.html](https://saxnbt.tk/SaxOS/os.html) for like the second time, and I see a tetris button... So I press it, and all I see is "404 PAGE NOT FOUND"

Is this intentional, or not ready, If so, I have my answer, if it is not intentional, **fix it I want to play tetris**

**Comment by Roizor** [comment]
that's just the saxos experience:tm:

**Comment by saxnbt** [comment]
@slvoog I haven't  yet implemented the required code and stuff for the tetris game, if you are using the demo from saxnbt.tk it shows a 404 because I simply just didn't implement the tetris window yet. The next bug fix will include tetris.
